<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SPTushonka.Common" Version="4.1.5" />
        <PackageReference Include="SPTushonka.DI" Version="4.1.5" />
        <PackageReference Include="SPTushonka.Reflection" Version="4.1.5" />
        <PackageReference Include="SPTushonka.Server.Core" Version="4.1.5" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Config\config.jsonc">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <Target Name="PackageMod" AfterTargets="Build">
        <PropertyGroup>
            <Author>gorecreek</Author>
            <Version>1.0.0</Version>
            <FolderName>$(Author)-$(AssemblyName)</FolderName>
            <ArchiveName>$(FolderName)-$(Version)</ArchiveName>
            <ModsRoot>$(TargetDir)SPT_Runtime\user\mods\$(FolderName)</ModsRoot>
        </PropertyGroup>

        <ItemGroup>
            <ModFiles Include="$(TargetPath)" />
            <ModFiles Include="$(TargetDir)Config\config.jsonc" />
        </ItemGroup>

        <Message Text="Creating folder structure [$(ModsRoot)]..." Importance="High" />
        <MakeDir Directories="$(ModsRoot)" />
        <Copy SourceFiles="@(ModFiles)" DestinationFolder="$(ModsRoot)" />

        <Message Text="Zipping [$(TargetDir)$(ArchiveName).zip]..." Importance="High" />

        <ZipDirectory
            SourceDirectory="$(OutputPath)\SPT_Runtime"
            DestinationFile="$(TargetDir)$(ArchiveName).zip"
            Overwrite="true" />

        <Message Text="Mod packaged successfully." Importance="High" />
    </Target>
</Project>